sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Tt010610
  alioss:
    endpoint: your endpoint
    access-key-id:  your accessId
    access-key-secret: your keySecret
    bucket-name: your bucketName
  redis:
    host: localhost
    port: 6379
    password: 20010610
    database: 0